# This is my own action yaml file and it is NOT TESTED. Use at your own risk!

name: R CMD check --as-cran

on:
  push:
    branches: [ master, fix-actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build on ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R: [ '4.3.1' ]

    steps:
      - uses: actions/checkout@master
      - name: Get system information
        run: |
          sudo apt-get install inxi
          inxi --color 0 --system --repos --disk --memory
      - name: Install R-related dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libgit2-dev
          sudo apt-get install libssh2-1-dev
      - name: Set up R ${{ matrix.R }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.R }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "devtools"))
          devtools::install_dev_deps(pkg = ".", dependencies = TRUE)
        shell: Rscript {0}
      - name: R Check
        run: devtools::check()
#      - name: Check dependencies with makefile
#        run: make deps
#      - name: Running make - documentation
#        run: make clean docs
#      - name: Running make - building
#        run: make build
#      - name: Running make - check with CRAN
#        run: make check-cran
